#!/bin/sh
set -e

case "$1" in
    configure)
        echo ""
        echo "Levin has been installed successfully!"
        echo ""
        echo "To get started:"
        echo "  1. Run 'levin' once to create default configuration"
        echo "  2. Edit ~/.config/levin/levin.toml to customize settings"
        echo "  3. Enable the service: systemctl --user enable levin"
        echo "  4. Start the service: systemctl --user start levin"
        echo ""
        echo "For more information, visit: https://github.com/bjesus/levin"
        echo ""
        ;;
esac

#DEBHELPER#

exit 0
